name: Cypress Tests
on:
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24        

      - name: Install dependencies
        run: npm ci               

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6   
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
