name: Cypress Tests
on:
 push:
   branches:
     - main
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: 20
     - run: npm install
     - run: npx cypress run --record
       env:
         CYPRESS_RECORD_KEY: ${{ secrets.6370cce8-4515-465b-9fc3-c38fa0374b8f }}
